name: Build LLVM

on:
  workflow_dispatch:
    inputs:
      llvm_ref:
        description: 'LLVM branch, tag, or Full SHA'
        required: true
        default: 'llvm-r547379-release'
      vendor_string:
        description: 'Vendor string for the build'
        required: true
        default: 'Mayuri'

permissions:
  contents: write

jobs:
  fedora:
    uses: ./.github/workflows/build-fedora.yml
    with:
      llvm_ref: ${{ inputs.llvm_ref }}
      vendor_string: ${{ inputs.vendor_string }}
      caller_run_id: ${{ github.run_id }}
    secrets: inherit

  bookworm:
    uses: ./.github/workflows/build-debian.yml
    with:
      llvm_ref: ${{ inputs.llvm_ref }}
      vendor_string: ${{ inputs.vendor_string }}
      debian_codename: bookworm
      caller_run_id: ${{ github.run_id }}
    secrets: inherit
